language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
env:
  - DJANGO=1.4.20
  - DJANGO=1.5.12
  - DJANGO=1.6.11
  - DJANGO=1.7.7
  - DJANGO=1.8.3
before_install:
  - export DJANGO_SETTINGS_MODULE=jet.tests.settings
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install importlib; fi
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install . --use-mirrors
script:
  - python manage.py test jet
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=1.6.11
    - python: 2.6
      env: DJANGO=1.7.7
    - python: 2.6
      env: DJANGO=1.8.3
    - python: 3.2
      env: DJANGO=1.4.20
    - python: 3.3
      env: DJANGO=1.4.20
    - python: 3.4
      env: DJANGO=1.4.20
    - python: pypy
      env: DJANGO=1.4.20
    - python: pypy
      env: DJANGO=1.5.12
